// src/utils/latexGenerator.js
// Matches Jake Gutierrez's resume format exactly

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

function esc(str = "") {
  return String(str)
    .replace(/\\/g,  "\\textbackslash{}")
    .replace(/&/g,   "\\&")
    .replace(/%/g,   "\\%")
    .replace(/\$/g,  "\\$")
    .replace(/#/g,   "\\#")
    .replace(/_/g,   "\\_")
    .replace(/\{/g,  "\\{")
    .replace(/\}/g,  "\\}")
    .replace(/~/g,   "\\textasciitilde{}")
    .replace(/\^/g,  "\\textasciicircum{}")
    .trim();
}

function toBullets(text = "") {
  const lines = text
    .split("\n")
    .map((l) => l.replace(/^[•\-]\s*/, "").trim())
    .filter(Boolean);
  if (!lines.length) return "";
  return [
    "      \\resumeItemListStart",
    ...lines.map((l) => `        \\resumeItem{${esc(l)}}`),
    "      \\resumeItemListEnd",
  ].join("\n");
}

function makeLink(url = "", display = "") {
  if (!url) return "";
  const href = url.startsWith("http") ? url : `https://${url}`;
  return `\\href{${href}}{\\underline{${esc(display || url)}}}`;
}

// ─────────────────────────────────────────────────────────────────────────────
// PREAMBLE — exactly Jake's format
// ─────────────────────────────────────────────────────────────────────────────

const PREAMBLE = `%-------------------------
% Resume in Latex
% Generated by ResumeForge
% Based on Jake Gutierrez's template
% License : MIT
%------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\input{glyphtounicode}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}
\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

% Sections formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

\\pdfgentounicode=1

%-------------------------
% Custom commands
\\newcommand{\\resumeItem}[1]{
  \\item\\small{
    {#1 \\vspace{-2pt}}
  }
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeSubSubheading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\textit{\\small#1} & \\textit{\\small #2} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small#1 & #2 \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeSubItem}[1]{\\resumeItem{#1}\\vspace{-4pt}}

\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}

\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}`;

// ─────────────────────────────────────────────────────────────────────────────
// SECTION BUILDERS
// ─────────────────────────────────────────────────────────────────────────────

function buildHeader(personal = {}, contact = {}) {
  const fullName =
    `${esc(personal.firstName || "")} ${esc(personal.lastName || "")}`.trim() || "Your Name";

  // Build each contact item — only include if filled
  const parts = [
    contact.phone
      ? `\\small ${esc(contact.phone)}`
      : null,
    contact.email
      ? `\\href{mailto:${contact.email}}{\\underline{${esc(contact.email)}}}`
      : null,
    contact.linkedin
      ? makeLink(contact.linkedin, contact.linkedin.replace(/^https?:\/\//, ""))
      : null,
    contact.github
      ? makeLink(contact.github, contact.github.replace(/^https?:\/\//, ""))
      : null,
    contact.portfolio
      ? makeLink(contact.portfolio, contact.portfolio.replace(/^https?:\/\//, ""))
      : null,
  ].filter(Boolean);

  const contactLine = parts.join(" $|$ ");
  const locationLine = contact.location ? `\\small ${esc(contact.location)} $|$ ` : "";

  return `%----------HEADING----------
\\begin{center}
    \\textbf{\\Huge \\scshape ${fullName}} \\\\ \\vspace{1pt}
    ${locationLine}${contactLine}
\\end{center}`;
}

function buildSummary(personal = {}) {
  if (!personal.summary) return "";
  return `%-----------SUMMARY-----------
\\section{Summary}
  \\resumeSubHeadingListStart
    \\resumeSubItem{${esc(personal.summary)}}
  \\resumeSubHeadingListEnd`;
}

function buildEducation(education = []) {
  const entries = education.filter((e) => e.institution || e.degree);
  if (!entries.length) return "";

  const rows = entries.map((e) => {
    const dateRange = [e.startYear, e.endYear].filter(Boolean).join(" -- ");
    const gpaLine   = e.gpa ? `\n      \\resumeItemListStart\n        \\resumeItem{GPA: ${esc(e.gpa)}}\n      \\resumeItemListEnd` : "";
    return `    \\resumeSubheading
      {${esc(e.institution)}}{${esc(e.location || "")}}
      {${esc(e.degree)}}{${esc(dateRange)}}${gpaLine}`;
  });

  return `%-----------EDUCATION-----------
\\section{Education}
  \\resumeSubHeadingListStart
${rows.join("\n")}
  \\resumeSubHeadingListEnd`;
}

function buildExperience(experience = []) {
  const entries = experience.filter((e) => e.company || e.role);
  if (!entries.length) return "";

  const rows = entries.map((e) => {
    const dateRange = [e.startDate, e.endDate].filter(Boolean).join(" -- ");
    const bullets   = toBullets(e.description);
    return `    \\resumeSubheading
      {${esc(e.role)}}{${esc(dateRange)}}
      {${esc(e.company)}}{}
${bullets}`;
  });

  return `%-----------EXPERIENCE-----------
\\section{Experience}
  \\resumeSubHeadingListStart
${rows.join("\n\n")}
  \\resumeSubHeadingListEnd`;
}

function buildProjects(projects = []) {
  const entries = projects.filter((p) => p.name);
  if (!entries.length) return "";

  const rows = entries.map((p) => {
    const techPart  = p.techStack ? `\\emph{${esc(p.techStack)}}` : "";
    const linkPart  = p.link      ? ` $|$ ${makeLink(p.link, "Link")}` : "";
    const namePart  = `\\textbf{${esc(p.name)}}`;
    const heading   = [namePart, techPart].filter(Boolean).join(" $|$ ");
    const bullets   = toBullets(p.description);
    return `      \\resumeProjectHeading
          {${heading}${linkPart}}{}
${bullets}`;
  });

  return `%-----------PROJECTS-----------
\\section{Projects}
    \\resumeSubHeadingListStart
${rows.join("\n")}
    \\resumeSubHeadingListEnd`;
}

function buildSkills(skills = []) {
  if (!skills.length) return "";

  // Group into max 6 per row labelled Languages, Frameworks, Tools, Libraries
  const labels  = ["Languages", "Frameworks", "Developer Tools", "Libraries"];
  const size    = Math.ceil(skills.length / 4);
  const chunks  = [];
  for (let i = 0; i < skills.length; i += size) {
    chunks.push(skills.slice(i, i + size));
  }

  const rows = chunks
    .map((chunk, i) => {
      const label = labels[i] || `Skills ${i + 1}`;
      return `     \\textbf{${label}}{: ${chunk.map(esc).join(", ")}}`;
    })
    .join(" \\\\\n");

  return `%
%-----------PROGRAMMING SKILLS-----------
\\section{Technical Skills}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
${rows}
    }}
 \\end{itemize}`;
}

function buildCertifications(certifications = []) {
  const entries = certifications.filter((c) => c.name);
  if (!entries.length) return "";

  const rows = entries.map((c) => {
    const dateStr = [c.issueDate, c.expiryDate].filter(Boolean).join(" -- ");
    return `    \\resumeSubheading
      {${esc(c.name)}}{${esc(dateStr)}}
      {${esc(c.issuer)}}{}`;
  });

  return `%-----------CERTIFICATIONS-----------
\\section{Certifications}
  \\resumeSubHeadingListStart
${rows.join("\n")}
  \\resumeSubHeadingListEnd`;
}

function buildAchievements(achievements = []) {
  const entries = achievements.filter((a) => a.title);
  if (!entries.length) return "";

  const items = entries.map((a) => {
    const year = a.year        ? ` (${esc(a.year)})`        : "";
    const desc = a.description ? ` -- ${esc(a.description)}` : "";
    return `    \\resumeItem{\\textbf{${esc(a.title)}}${year}${desc}}`;
  });

  return `%-----------ACHIEVEMENTS-----------
\\section{Achievements}
  \\resumeItemListStart
${items.join("\n")}
  \\resumeItemListEnd`;
}

// ─────────────────────────────────────────────────────────────────────────────
// MAIN EXPORT
// ─────────────────────────────────────────────────────────────────────────────

export function generateLatex(data = {}) {
  const {
    personal       = {},
    contact        = {},
    education      = [],
    experience     = [],
    skills         = [],
    projects       = [],
    certifications = [],
    achievements   = [],
  } = data;

  // Section order matches Jake's resume exactly:
  // Header → Education → Experience → Projects → Skills → Certs → Achievements
  const sections = [
    buildHeader(personal, contact),
    buildSummary(personal),
    buildEducation(education),
    buildExperience(experience),
    buildProjects(projects),
    buildSkills(skills),
    buildCertifications(certifications),
    buildAchievements(achievements),
  ].filter(Boolean).join("\n\n\n");

  return `${PREAMBLE}\n\n%-------------------------------------------\n%%%%%%  RESUME STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n\n\\begin{document}\n\n${sections}\n\n%-------------------------------------------\n\\end{document}`;
}

export async function copyToClipboard(text) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

export function openInOverleaf(latexCode) {
  const form  = document.createElement("form");
  form.method = "POST";
  form.action = "https://www.overleaf.com/docs";
  form.target = "_blank";
  const input = document.createElement("input");
  input.type  = "hidden";
  input.name  = "snip";
  input.value = latexCode;
  form.appendChild(input);
  document.body.appendChild(form);
  form.submit();
  document.body.removeChild(form);
}